language: python
python:
- '2.7'
env:
- DB=sqlite
install:
- . $HOME/.nvm/nvm.sh
- nvm install stable
- nvm use stable
- npm install
- make install-dev
script:
- make test-travis
before_deploy:
- make deploy-ready
deploy:
  provider: heroku
  api_key:
    secure: 3C6+2kxAAXC8ntwcl3+P8fxBCnWVn4AZiTBcU7nePzqUub4he6LvECrh0laUrBHXFW6x0CcJfNfEyM5bM72KiLPWFZ8t/4gNxC5pTC3HDjxnC9GToHT4VHoquXD3HV/y01wjITAziN4uyoqbpyB0fEHjls5N8Fa2eGe0GzQAUpf4IuUT7+MI/cD9JsAV0NW4csrZD/OJeS+xYlsgAXa1PVJyOfMi4hPLc3ex73D083Rufix7DfaE1FJk6cewcZVPLjS1Vzq6g/F7yQS1/sbLbDV9OZubvvxgp8gYdfJ4LdLob425u+3aZbWeIJbJ9+NrfakXlRBeW8JU2dNf2sFOEZuQruPz35ajOF1v6kP/vgYij809F7FuOaKE8mj3Xy1OFdzA2vN/4pWsadNyoT43ffb2gJCZdzcnKOeyVTNyjklytSKZLomDko7aePGZep591ziqZFPjnPJy5MHVtnfwPypzOTFBc/fVVWiNt4vM6F5nQo6Ly6VHBELSJ/VLprknaM5PCSWawRbfJ8h5kYkt8CCfU69DVxm+VcoT4lnQ/KSfkMYBK/ExADYwq02Q1bIcDdEv3jBEPROXpHRLTB+wdnbotMm3YtgARX4Ft/2KhK1X5hNAzvjA6KdBRp1H43/T5ogawTRvdM6ShMDYRWyMgxSbo2u4/z+X2xPR0A3n1WU=
  app: gbl-gifboard
  on:
    repo: gabriel-card/gifboard
